-- 제휴식당 어디지? Supabase Postgres schema
-- FastAPI also runs SQLAlchemy create_all() on startup, but this file is useful
-- when the schema should be reviewed/applied from the Supabase SQL editor.

create table if not exists affiliations (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  type varchar(20) not null check (type in ('university', 'college', 'department')),
  parent_id bigint references affiliations(id) on delete set null
);

create table if not exists restaurants (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  category varchar(40) not null,
  address varchar(255) not null default '',
  latitude double precision not null,
  longitude double precision not null,
  phone varchar(40) not null default '',
  opening_hours varchar(255) not null default '',
  menu_summary text not null default '',
  image_url varchar(500) not null default '',
  rating_average double precision not null default 0,
  review_count integer not null default 0,
  status varchar(20) not null default 'active',
  created_at timestamp not null default now()
);

create table if not exists partnerships (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  affiliation_id bigint not null references affiliations(id) on delete cascade,
  benefit_type varchar(30) not null,
  discount_rate double precision not null default 0,
  fixed_discount integer not null default 0,
  service_item varchar(160) not null default '',
  estimated_cash_value integer not null default 0,
  min_order_amount integer not null default 0,
  min_people integer not null default 1,
  payment_method varchar(40) not null default '',
  application_scope varchar(30) not null default 'ALL_GROUP',
  verification_method varchar(160) not null default '학생증',
  eligibility_description text not null default '',
  start_date date not null,
  end_date date not null,
  status varchar(20) not null default 'pending',
  source varchar(80) not null default 'admin',
  last_verified_at timestamp,
  created_at timestamp not null default now(),
  unique (restaurant_id, affiliation_id, start_date)
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  content text not null default '',
  author_name varchar(80) not null default '익명',
  is_hidden boolean not null default false,
  admin_reply text not null default '',
  created_at timestamp not null default now()
);

create table if not exists reports (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  report_type varchar(40) not null,
  content text not null,
  status varchar(20) not null default 'open',
  created_at timestamp not null default now()
);

create table if not exists usage_events (
  id bigint generated by default as identity primary key,
  restaurant_id bigint references restaurants(id) on delete set null,
  event_type varchar(30) not null,
  metadata_json text not null default '{}',
  created_at timestamp not null default now()
);

create table if not exists import_batches (
  id bigint generated by default as identity primary key,
  filename varchar(255) not null,
  status varchar(20) not null default 'preview',
  row_count integer not null default 0,
  errors_json text not null default '[]',
  created_at timestamp not null default now()
);

create table if not exists admin_sessions (
  id bigint generated by default as identity primary key,
  token varchar(128) unique not null,
  expires_at timestamp not null,
  created_at timestamp not null default now()
);

-- Supabase Auth profile mirror. Google authentication is handled by Supabase Auth;
-- the app stores only the profile fields needed for user-facing features.
create table if not exists users (
  id bigint generated by default as identity primary key,
  auth_user_id varchar(128) unique not null,
  email varchar(255) not null default '',
  name varchar(120) not null default '',
  avatar_url varchar(500) not null default '',
  last_login_at timestamp,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  restaurant_id bigint not null references restaurants(id) on delete cascade,
  created_at timestamp not null default now(),
  unique (user_id, restaurant_id)
);

create index if not exists idx_restaurants_category on restaurants(category);
create index if not exists idx_restaurants_status on restaurants(status);
create index if not exists idx_partnerships_restaurant on partnerships(restaurant_id);
create index if not exists idx_partnerships_affiliation on partnerships(affiliation_id);
create index if not exists idx_partnerships_status on partnerships(status);
create index if not exists idx_reports_status on reports(status);
create index if not exists idx_usage_events_type_created on usage_events(event_type, created_at);
create index if not exists idx_users_auth_user_id on users(auth_user_id);
create index if not exists idx_favorites_user_id on favorites(user_id);
